### ISSUE TITLE
When running the demo in xcode it crushed with : dyld: Library not loaded 

### ISSUE THREAD

**Issue by Asher1000** [cats-oss/Sica#10]
Fix for that :
Go to the xcode **target** (sicaDemo) settings, **General** Tab,  and add Sica.Framework to **Embedded Binaries**

**Comment by funzin** [comment]
Hi, Asher1000.

If you want to check demo, open `SicaDemo.xcworkspace`. You can see that it works correctly

**Comment by Asher1000** [comment]
Hi funzin,
I just download it again (just incase I'm missed something, and for not confusing other users)
Open the zip file
Open the  SicaDemo.**xcworkspace**
Setting the developer name
and again the app crushed with the same error  : dyld: Library not loaded 
then I fix it like I wrote before and it works again.

**Comment by funzin** [comment]
I could confirm that demo app crashed when running on device.
I merged this PR(https://github.com/cats-oss/Sica/pull/11) and then release `0.3.3`.
Please check demo app in that version.
