### ISSUE TITLE
Constraints manipulation

### ISSUE THREAD

**Issue by pgawlowski** [cats-oss/Sica#19]
Is it possible to manipulate view constraints using your lib?

**Comment by jrtibbetts** [comment]
I'm not the owner, but since this targets CoreAnimation and layers, it shouldn't have anything to do with things at the view level, including view constraints.

**Comment by funzin** [comment]
Hi, @pgawlowski 
(Thanks to replay! @jrtibbetts )

Sica can't manipulate view constraints.
